---
- name: Exercise 4
  gather_facts: False
  hosts: arista
  tasks:
    - name: Run template module to jinja2 template
      template:
        src: quest4.j2
        dest: "./configs/{{ inventory_hostname }}.txt"