---
# First play to print localhost
- name: Print localhost
  hosts: localhost
  gather_facts: False
  tasks:
    - debug:
        var: ansible_host

# Second play to print cisco information
- name: Print cisco group information
  hosts: cisco
  gather_facts: False
  tasks:
    - debug:
        var: ansible_connection

    - debug:
        var: ansible_host

